# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # OSX doesn't allow so don't do this explicit naming for now
  # config.vm.provider "virtualbox" do |v|
  #    v.name = "VDP_VISTA_GTM"
  # end

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "Official Ubuntu 12.04 current daily Cloud Image amd64"
  config.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  # config.vm.box_url = "http://domain.com/path/to/above.box"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 9430, host: 9430 # RPC Broker
  config.vm.network :forwarded_port, guest: 8001, host: 8001 # VistALink
  config.vm.network :forwarded_port, guest: 8080, host: 8080 # EWD.js
  config.vm.network :forwarded_port, guest: 8000, host: 8000 # EWD.js Webservices
  config.vm.network :forwarded_port, guest: 8081, host: 8081 # EWD VistA Term
  # New Forward VDP
  config.vm.network :forwarded_port, guest: 9000, host: 9000 # For FMQL Server
  config.vm.network :forwarded_port, guest: 9001, host: 9001 # For RPC Server
  config.vm.network :forwarded_port, guest: 9002, host: 9002 # For MVDM Server
  config.vm.network :forwarded_port, guest: 9010, host: 9010 # For RPC Server or RPC Sniffer
  config.vm.network :forwarded_port, guest: 9020, host: 9020 # For MVDM Client

  # New Forward Node Inspector
  config.vm.network :forwarded_port, guest: 5858, host: 5858 # for node-inspector (debug-port) 
  config.vm.network :forwarded_port, guest: 3001, host: 3001 # for node-inspector (web-port)    

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "10.2.2.100"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "./", "/vagrant"

  # Define primary box name for all VM providers
  # More VMs could be added here to build a multi-box install and provision
  # accordingly
  config.vm.define "OSEHRA VistA - Ubuntu", primary: true do |vista|
  end

  # added skip test
  config.vm.provision :shell do |s|
    s.path = "autoInstaller.sh"
    s.args = "-e -s -i " + "osehra"
  end
end
